### ISSUE TITLE
"All current offsets, etc. are USA N3DS only"

### ISSUE THREAD

**Issue by LightShellium** [nedwill/fasthax#12]
So it will only support 11.2.0-XXU? Because I want to use this on my 11.2.0-35E New 3DS (XL) model.
I know this shouldn't really be posted here, but I can't find any forums for fasthax (i know GBATemp but I want to be sure) and I don't want to brick my DS.

**Comment by Moocow9m** [comment]
From what I have read on GBA temp it should work on all 3DS when it is finished.

**Comment by LightShellium** [comment]
I mean in this "alpha" phase.

**Comment by Moocow9m** [comment]
In that case IDK However I believe that it doesn't do anything that can brick you device but I may be wrong.

**Comment by Intege-rs** [comment]
Please do more research :D. Yes this will support o3ds and it's already confirmed to work for other n3ds devices such as Jap and Eur. Nedwill has them retweeted on his Twitter.

**Comment by LightShellium** [comment]
lol, I should have checked his twitter...
