### ISSUE TITLE
O3DS Attempt

### ISSUE THREAD

**Issue by DaBlueOne** [nedwill/fasthax#23]
I have no idea if it worked or not, but, it seems like it did?

Starts "beginning attempt 0xXXXX",
"we won",
then goes to "[+] UAF succeeded and local backdoor installed"
if anyone can confirm (or disprove) that it worked please do tell.
(image link: http://i.imgur.com/IfxJmOY.jpg)

**Comment by martinnnnnnnnnnnnnnnnnnn** [comment]
Ned is cranking out commits like no tomorrow. I think he's trying to fix that freeze. For me on a n3ds 11.0, I've gotten a freeze w/ the last 3 builds on "[+] UAF succeeded and local backdoor installed."

**Comment by lotsa-spaghetti** [comment]
It won't work for now. But nedwill keeps working and I think it may work until tomorrow.

**Comment by DaBlueOne** [comment]
Ah, thanks.

**Comment by kev1ncal** [comment]
@DaBlueOne bru can you upload the file? I can't build fasthax on my PC so,

**Comment by Moocow9m** [comment]
@joken767 this issue is closed.

**Comment by trilleplay** [comment]
@joken767 go to the builds section of this page and download fasthax.3dsx 

--The more you know--
:)
