### ISSUE TITLE
How would I go about compiling this now?

### ISSUE THREAD

**Issue by ghost** [nedwill/fasthax#25]

**Comment by Moocow9m** [comment]
.... Did you not read the readme? This is for issues not questions that are already answered in the readme

**Comment by ghost** [comment]
I know but when i ran "make" it gave me an error and im pretty sure i have everything

**Comment by Moocow9m** [comment]
What is the error?

**Comment by ghost** [comment]
> /bin/sh:`
 -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `make --no-print-directory -C build -f /c/Users/User/Documents/fasthax-master/Makefile'
make: *** [build] Error 2

**Comment by kurocygnus** [comment]
Just update the CTRULIB.

**Comment by ghost** [comment]
Mmmm, Alright.

**Comment by ShinichiKudoSan** [comment]
[fasthax-master.zip](https://github.com/nedwill/fasthax/files/681439/fasthax-master.zip)

Here you go guy if you really need it

**Comment by nedwill** [comment]
I'm maintaining releases now that we're in beta: https://github.com/nedwill/fasthax/releases
