### ISSUE TITLE
Can someone compile the last version of fasthax for me plzz ???

### ISSUE THREAD

**Issue by K1000Rkraft** [nedwill/fasthax#31]
i need it

**Comment by kade-robertson** [comment]
All of the tools are available to you for free! :)

Install DevKitPro: https://sourceforge.net/projects/devkitpro/
Install ctrulib: https://github.com/smealum/ctrulib (In fact, I think ctrulib is included with the latest DevKitPro installation, so you might not need this)

Then you can use `make` to compile this.

------

If you are just looking to downgrade, the files from the guide work fine.

**Comment by kev1ncal** [comment]
can't build anything

**Comment by kade-robertson** [comment]
If you can't figure out how to build this you probably shouldn't be using it yet..

**Comment by K1000Rkraft** [comment]
Where is make ??

**Comment by blackwing182** [comment]
Gerrit noobs. I even set a build bot 😂😂😂 this does not require a high end pc any pc cand build it (mine have worst specs ever) and it compiles it just fine (Miui Port Team Member Here)

**Comment by trilleplay** [comment]
Okay K1000Rkraft if you do not know basic compiling and coding you should not be here in the first place! Wait until nedwill has made a website like for soundhax! Or just don't care! (Or maybe sit and learn basic UNIX commands for a day)

**Comment by nedwill** [comment]
https://github.com/nedwill/fasthax/releases
