### ISSUE TITLE
Something with a n3ds xl

### ISSUE THREAD

**Issue by ruperghost** [nedwill/fasthax#5]
So when I launched fasthax this happened. 
![fasthaxfail](https://cloud.githubusercontent.com/assets/24844756/21569248/28b232bc-ce89-11e6-9582-a59e47cd32a3.JPG)

Anything wrong with my 3ds?

**Comment by spiritfire123123123213** [comment]
How do you install let me try dont have cfw

**Comment by kurocygnus** [comment]
No, you just need to keep trying until it triggers.

**Comment by ruperghost** [comment]
ok

**Comment by ruperghost** [comment]
i'll try it

**Comment by ruperghost** [comment]
Finally it worked

**Comment by spiritfire123123123213** [comment]
HOW DO YOU INSTAL THISSS

**Comment by ghost** [comment]
@spiritfire123123123213 http://moger.net/fasthax.php
