### ISSUE TITLE
Black and Red Screen

### ISSUE THREAD

**Issue by cunninghamx** [nedwill/fasthax#55]
Latest release, only getting a black screen on top and red screen on bottom.

**Comment by chivs688** [comment]
Same issue on 2DS 11.2.0, tried 1.0, Beta 4 and Beta 1.

**Comment by d3m3vilurr** [comment]
it's probably stability issus of o3ds.
can you check multiple times?

**Comment by ViolentSempie** [comment]
I've had this issue aswell, however, it seemed that the top 2 items in the homebrew menu _fasthax is not the one you should load. Instead scroll down a bit and you'll see a red ds icon with fasthax, that is the one you should click.

**Comment by cunninghamx** [comment]
@RukiaXi  this was it thanks.
