### ISSUE TITLE
2DS Fasthax Stability

### ISSUE THREAD

**Issue by ghost** [nedwill/fasthax#58]
Hey ned, is fasthax 100% stable on 2DS? Can i run it without get bricked?

**Comment by nedwill** [comment]
Yes, in my tests it always works now. Even if it fails it cannot brick your device.

**Comment by ghost** [comment]
It means we can have cia installers like FBI (for educational use) ?

**Comment by nedwill** [comment]
I don't know; you'll have to ask the maintainer of that program.

**Comment by phtom** [comment]
Is it possible to install homebrew cia after running fasthax?

**Comment by ghost** [comment]
Have  you tested fasthax on 2DS 11.2?

**Comment by ghost** [comment]
CONFIRMED: Fasthax working on 2DS 11.2.0.35E. It installs in less than 5 seconds :D

**Comment by fuzun** [comment]
@nedwill I can confirm too. Fasthax working perfectly @ 2ds 11.2.0.35E . Maybe its time to make a final release.

But there is a thing that I notice, it is not permanent for me. I need to open homebrew after each start and use fasthax again. (I am not into 3ds hacking so there may be things that I did not notice)

**Comment by nedwill** [comment]
It's not meant to be permanent. This is why it's safe to say it won't brick: it doesn't write to the NAND.

**Comment by Slashin-it-up** [comment]
I can confirm working. I used it to downgrade
