### ISSUE TITLE
running "make" leads to [error 2]

### ISSUE THREAD

**Issue by grifnelle** [nedwill/fasthax#8]
trying to follow the steps @nedwill said but I get error 2

/bin/sh: -c: line 1: syntax error: unexpected end of file
make: *** [build] Error 2

not sure what i did wrong, I ran make with devkitpro but thats all i get is an error

**Comment by lotsa-spaghetti** [comment]
There seems to be something wrong with your build system. But I don't know what exactly. Try reinstalling devkit and devkitarm. Also, build it from devkitpro's msys.

**Comment by grifnelle** [comment]
i just installed devkitpro like 20mins ago, and not sure about how to build from msys, unfamiliar with the program
